/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaonline;

import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.Scanner;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ferna
 */
public class MenuDeCompras extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuDeCompras
     */
    
    
    public MenuDeCompras() {
        initComponents();
        this.TablaCompra.setModel(modelo);
        this.modelo.addColumn("Categoria");
        this.modelo.addColumn("Producto");
        this.modelo.addColumn("Codigo");
        this.modelo.addColumn("Precio");
        this.modelo.addColumn("Cantidad");
        this.modelo.addColumn("Precio por Cantidad");
        this.modelo.addColumn("Fecha");
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboProductos = new javax.swing.JComboBox<>();
        btnCodigo = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtTotalproducto = new javax.swing.JTextField();
        btnalCarrito = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnTotalaPagar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaCompra = new javax.swing.JTable();
        btnLimpiarTabla = new javax.swing.JButton();
        btnQuitarCompra = new javax.swing.JButton();
        btnNetoaPagar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNetoaPagar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnGuardarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("    Tiendita Flanderijilla Online");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 102)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 204)));

        jLabel4.setText("Seleccione Categoria:");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abarrotes", "Liquidos", "Aseo", "Congelados", "Ofertas" }));
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Productos:");

        cboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductosActionPerformed(evt);
            }
        });

        btnCodigo.setText("Codigo del producto");
        btnCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoActionPerformed(evt);
            }
        });

        jLabel6.setText("          Cantidad");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnalCarrito.setText("Al Carrito!!!");
        btnalCarrito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnalCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalCarritoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel12.setText("Fecha:");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel13.setText("             Precio");

        btnTotalaPagar.setText("Total a Pagar");
        btnTotalaPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTotalaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalaPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtPrecio)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnalCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnTotalaPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotalaPagar))
                        .addGap(89, 89, 89)
                        .addComponent(btnalCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("   Sistema de Compras");

        jLabel11.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText(" Productos en OFERTA!!!");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Compras"));
        jPanel2.setForeground(new java.awt.Color(255, 0, 102));

        TablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaCompra.setEditingColumn(7);
        TablaCompra.setEditingRow(9);
        jScrollPane3.setViewportView(TablaCompra);

        btnLimpiarTabla.setText("Limpiar Tabla");
        btnLimpiarTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaActionPerformed(evt);
            }
        });

        btnQuitarCompra.setText("Quitar Compra");
        btnQuitarCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarCompraActionPerformed(evt);
            }
        });

        btnNetoaPagar.setText("Neto a Pagar");
        btnNetoaPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNetoaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetoaPagarActionPerformed(evt);
            }
        });

        jLabel10.setText("Neto a Pagar:");

        jButton3.setText("Salir");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnGuardarCompra.setText("Guardar Compra");
        btnGuardarCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuitarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNetoaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnGuardarCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNetoaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiarTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuitarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNetoaPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetoaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(35, 35, 35)
                .addComponent(btnGuardarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jTextArea1.setBackground(new java.awt.Color(153, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText(" -LLeve 5 paquetes de Tallarines N°5 \n  con 3 Salsas de 200g a $990\n -6 Botellas de Vino Tinto Gato 700cc \n  a $2000\n -Detergente Liquido 4L con Lavalosa 750ml a $1150\n -Te Supremo 100 Unidades con 1kg Azucar \n  grado2 a $1000\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    DefaultTableModel modelo=new DefaultTableModel();
    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        // TODO add your handling code here:
        int x=this.modelo.getRowCount();
        for(int y=0; y<=x; y++){
            this.modelo.removeRow(0);
        }
        this.txtNetoaPagar.setText("");
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void btnQuitarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarCompraActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.TablaCompra.getSelectedRow());
    }//GEN-LAST:event_btnQuitarCompraActionPerformed

    private void btnNetoaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetoaPagarActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatoria1=0;
        int totalrow= TablaCompra.getRowCount();
        totalrow-=1;
        for (int i = 0; i <= (totalrow); i++){
            sumatoria= Double.parseDouble(String.valueOf(TablaCompra.getValueAt(i, 5)));
            sumatoria1+=sumatoria;
        }
        txtNetoaPagar.setText("$ "+String.valueOf(sumatoria1));
    }//GEN-LAST:event_btnNetoaPagarActionPerformed

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        // TODO add your handling code here:
        if(cboCategoria.getSelectedItem().equals("Abarrotes")){
            cboProductos.removeAllItems();
            cboProductos.addItem("Arroz 1kg");
            cboProductos.addItem("Tallarines N°5 400g");
            cboProductos.addItem("Aceite 1L");
            cboProductos.addItem("Salsa Tomate 200g");
            cboProductos.addItem("Azucar 1kg");
            cboProductos.addItem("Sal 1kg");
        }else
            if(cboCategoria.getSelectedItem().equals("Liquidos")){
                cboProductos.removeAllItems();
                cboProductos.addItem("Jugos watt 1L");
                cboProductos.addItem("Agua Mineral 1L");
                cboProductos.addItem("Coca-Cola 1L");
                cboProductos.addItem("Red Bull 200cc");
                cboProductos.addItem("Vino Tinto Gato 700cc");
            }else
            if(cboCategoria.getSelectedItem().equals("Aseo")){
                cboProductos.removeAllItems();
                cboProductos.addItem("Detergente Liquido 4L");
                cboProductos.addItem("Lavaloza 750ml");
                cboProductos.addItem("Trapero Humedo Desechable 10Unidades");
                cboProductos.addItem("Virutilla");
                cboProductos.addItem("Limpia Vidrios 500ml");
                cboProductos.addItem("Poett 900 ml");
            }else
            if(cboCategoria.getSelectedItem().equals("Congelados")){
                cboProductos.removeAllItems();
                cboProductos.addItem("Bolsa Papas Duquesas 1kg");
                cboProductos.addItem("Croquetas de Pollo 80g");
                cboProductos.addItem("Choclo Congelado 1kg");
                cboProductos.addItem("Arvejas Congeladas 500g");
                cboProductos.addItem("Ensalada Primavera 500g");
            }else
            if(cboCategoria.getSelectedItem().equals("Ofertas")){
                cboProductos.removeAllItems();
                cboProductos.addItem("5 paquetes de Tallarines N°5 + con 3 Salsas de 200g");
                cboProductos.addItem("6 Botellas de Vino Tinto Gato 700cc");
                cboProductos.addItem("Detergente Liquido 4L + Lavalosa 750ml");
                cboProductos.addItem("Te Supremo 100 Unidades + 1kg Azucar");
            }
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductosActionPerformed
        // TODO add your handling code here:
        if(cboProductos.getSelectedItem().equals("Arroz 1kg")){
            txtPrecio.setText("1090");
        }else
            if(cboProductos.getSelectedItem().equals("Tallarines N°5 400g")){
            txtPrecio.setText("700");
        }else
            if(cboProductos.getSelectedItem().equals("Aceite 1L")){
            txtPrecio.setText("1570");
        }else
            if(cboProductos.getSelectedItem().equals("Salsa Tomate 200g")){
            txtPrecio.setText("570");
        }else
            if(cboProductos.getSelectedItem().equals("Azucar 1kg")){
            txtPrecio.setText("770");
        }else 
            if(cboProductos.getSelectedItem().equals("Sal 1kg")){
            txtPrecio.setText("350");
        }else 
           if(cboProductos.getSelectedItem().equals("Jugos watt 1L")){
            txtPrecio.setText("1000");
        }else
           if(cboProductos.getSelectedItem().equals("Agua Mineral 1L")){
            txtPrecio.setText("700");
        }else 
           if(cboProductos.getSelectedItem().equals("Coca-Cola 1L")){
            txtPrecio.setText("1990");
        }else 
           if(cboProductos.getSelectedItem().equals("Red Bull 200cc")){
            txtPrecio.setText("1350");
        }else 
           if(cboProductos.getSelectedItem().equals("Vino Tinto Gato 700cc")){
            txtPrecio.setText("4690");
        }else
           if(cboProductos.getSelectedItem().equals("Detergente Liquido 4L")){
            txtPrecio.setText("10190");
        }else
           if(cboProductos.getSelectedItem().equals("Lavaloza 750ml")){
            txtPrecio.setText("1200");
        }else
           if(cboProductos.getSelectedItem().equals("Trapero Humedo Desechable 10Unidades")){
            txtPrecio.setText("2740");
        }else
           if(cboProductos.getSelectedItem().equals("Virutilla")){
            txtPrecio.setText("990");
        }else
           if(cboProductos.getSelectedItem().equals("Limpia Vidrios 500ml")){
            txtPrecio.setText("1960");
        }else
           if(cboProductos.getSelectedItem().equals("Poett 900 ml")){
            txtPrecio.setText("1190");
        }else
           if(cboProductos.getSelectedItem().equals("Bolsa Papas Duquesas 1kg")){
            txtPrecio.setText("900");
        }else
           if(cboProductos.getSelectedItem().equals("Croquetas de Pollo 80g")){
            txtPrecio.setText("380");
        }else
           if(cboProductos.getSelectedItem().equals("Choclo Congelado 1kg")){
            txtPrecio.setText("980");
        }else
           if(cboProductos.getSelectedItem().equals("Arvejas Congeladas 500g")){
            txtPrecio.setText("970");
        }else
           if(cboProductos.getSelectedItem().equals("Ensalada Primavera 500g")){
            txtPrecio.setText("1290");
        }else
           if(cboProductos.getSelectedItem().equals("5 paquetes de Tallarines N°5 + con 3 Salsas de 200g")){
            txtPrecio.setText("$990");
        }else
           if(cboProductos.getSelectedItem().equals("6 Botellas de Vino Tinto Gato 700cc")){
            txtPrecio.setText("2000");
        }else
           if(cboProductos.getSelectedItem().equals("Detergente Liquido 4L + Lavalosa 750ml")){
            txtPrecio.setText("1150");
        }else
           if(cboProductos.getSelectedItem().equals("Te Supremo 100 Unidades + 1kg Azucar")){
            txtPrecio.setText("1000");
        }
    }//GEN-LAST:event_cboProductosActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed
        // TODO add your handling code here:}
        Random codigo = new Random();
          int correlativo;
          for (int i=0; i<4; i++){
              
          }
          correlativo = codigo.nextInt(1111);
          txtCodigo.setText(""+correlativo);
    }//GEN-LAST:event_btnCodigoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
        txtCantidad.setText("");
        
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnTotalaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalaPagarActionPerformed
        // TODO add your handling code here:
        int producto, cantidad, total;
        producto= Integer.parseInt(txtPrecio.getText());
        cantidad= Integer.parseInt(txtCantidad.getText());
        total = producto*cantidad;
        txtTotalproducto.setText(""+total);
        if(total<0){
            txtTotalproducto.setText("ERROR");
        }
    }//GEN-LAST:event_btnTotalaPagarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.cboCategoria.setSelectedIndex(0);
        this.cboProductos.setSelectedIndex(0);
        JTextField caja;
        for(int i=0; i< jPanel1.getComponentCount();i++){
            if(jPanel1.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja=(JTextField)jPanel1.getComponent(i);
                caja.setText("");
                txtCodigo.requestFocus();
                txtPrecio.requestFocus();
                txtCantidad.requestFocus();
                txtFecha.requestFocus();
                txtTotalproducto.requestFocus();
            }
        }
         
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnalCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalCarritoActionPerformed
        // TODO add your handling code here:
       String [] info=new String[7];
       info[0]= this.cboCategoria.getSelectedItem().toString();
       info[1]= this.cboProductos.getSelectedItem().toString();
       info[2]= txtCodigo.getText();
       info[3]= txtPrecio.getText();
       info[4]= txtCantidad.getText();
       info[5]= txtTotalproducto.getText();
       info[6]= txtFecha.getText();
       modelo.addRow(info);
       
       
    }//GEN-LAST:event_btnalCarritoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompraActionPerformed
        // TODO add your handling code here:
        
        try{
            FileWriter salvar=new FileWriter("c:\\archivo\\archivo1.txt");
            for(int i=0; i<this.TablaCompra.getRowCount();i++){
            salvar.write(modelo.getValueAt(i, 0).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 1).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 2).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 3).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 4).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 5).toString()+"\n");
            salvar.write(modelo.getValueAt(i, 6).toString()+"\n");
            }
        salvar.close();
        JOptionPane.showMessageDialog(null, "Datos Guardados");
        
        }catch(Exception x){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_btnGuardarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCompra;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnGuardarCompra;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnNetoaPagar;
    private javax.swing.JButton btnQuitarCompra;
    private javax.swing.JButton btnTotalaPagar;
    private javax.swing.JButton btnalCarrito;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNetoaPagar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotalproducto;
    // End of variables declaration//GEN-END:variables
}
